name: Manual Dispatch Workflow

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  run-manual-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Print inputs
        run: |
          echo "Log Level: ${{ github.event.inputs.logLevel }}"
          echo "Tags: ${{ github.event.inputs.tags }}"
          echo "Environment: ${{ github.event.inputs.environment }}"
