name: Manual Dispatch Workflow

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level (recommended: info, warning, debug) or provide custom value'
        required: true
        default: 'warning'
        type: string
      tags:
        description: 'Run with tags?'
        required: false
        type: boolean
      environment:
        description: 'Environment (recommended: dev, staging, prod) or provide custom value'
        required: true
        default: 'dev'
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show provided inputs
        run: |
          echo "Log Level: ${{ github.event.inputs.logLevel }}"
          echo "Tags: ${{ github.event.inputs.tags }}"
          echo "Environment: ${{ github.event.inputs.environment }}"

      - name: Example conditional step (only runs if environment == prod)
        if: ${{ github.event.inputs.environment == 'prod' }}
        run: echo "🚀 Running production-specific job with logLevel=${{ github.event.inputs.logLevel }}"
